name: Playwright Tests/Zip Files/Publish Chrome Extension
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: |
        cd tests/e2e 
        npm ci
        cd ../../v2-client-react-ts
        npm ci
        npm run build
    - name: Install Playwright Browsers
      run: |
        cd tests/e2e
        npx playwright install --with-deps
    - name: Run Playwright tests
      run: |
        cd tests/e2e
        npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
 
  zip-files:
    if: github.ref == 'refs/heads/master' && success() && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: |
          cd v2-client-react-ts
          npm ci
      - name: Build
        run: |
          cd v2-client-react-ts
          npm run build
      - uses: vimtor/action-zip@v1.2
        with:
          files: v2-client-react-ts/build/
          dest: build.zip
      - name: Upload to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: 'publish'
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.SECRET }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          extension_id: ${{ secrets.EXTENSION_ID }}
          zip_file: build.zip
      - uses: actions/upload-artifact@v4
        with:
          name: v2ClientReactTsZipFile
          path: build.zip