name: Run Playwright Tests
on:
  push:
    branches: [ '*' ]
    paths:
      - 'tests/e2e/**'
      - 'v2-client-react-ts/**'
      - '.github/workflows/playwright-tests.yml'
  pull_request:
    branches: [ '*' ]
    paths:
      - 'tests/e2e/**'
      - 'v2-client-react-ts/**'
      - '.github/workflows/playwright-tests.yml'
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: |
        cd tests/e2e 
        npm ci
        cd ../../v2-client-react-ts
        npm ci
        npm run build
    - name: Install Playwright Browsers
      run: |
        cd tests/e2e
        npx playwright install --with-deps
    - name: Run Playwright tests
      run: |
        cd tests/e2e
        npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: tests/e2e/playwright-report/
        retention-days: 5
 